# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G7-FMSgHrvfbT2wRjWwUUpKAFQ71Ui28
"""

# 1.Massiv Yaratish
array_1d=np.arry([1,2,3,4,5])
array_2d=np.arry([1,2,3,,4,5])
#2. Matematik  operatsiyalar
sum_array =np.sum(array_1d)
mean_array=np.mean(array_1d)
product_array=np.prod(array_id)

print("1d massiv:" ,array_id)
print("2d Massiv:\n," array_2d)
print("Massivlar yig'indsi:",sum_array)
print("O'rtacha:" mean_array)
print("Ko'paytma:", product_array )